services:
  app:
    build: .
    image: ous-price-monitor:latest
    container_name: ous-price-monitor
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.price-monitor-http.entrypoints=http"
      - "traefik.http.routers.price-monitor-http.rule=Host(`price-monitor.thierryrenematos.tec.br`)"
      - "traefik.http.routers.price-monitor-http.middlewares=redirect-to-https"
      - "traefik.http.routers.price-monitor-https.entrypoints=https"
      - "traefik.http.routers.price-monitor-https.rule=Host(`price-monitor.thierryrenematos.tec.br`)"
      - "traefik.http.routers.price-monitor-https.tls=true"
      - "traefik.http.routers.price-monitor-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.price-monitor-service.loadbalancer.server.port=8000"
      - "traefik.http.routers.price-monitor-https.service=price-monitor-service"

networks:
  coolify:
    external: true
